package com.minichain.minichainsplayer

enum class BroadcastMessage {
    START_PLAYING,
    START_PLAYING_SONG,
    STOP_PLAYING,
    START_STOP_PLAYING_NOTIFICATION,
    PREVIOUS_SONG,
    NEXT_SONG,
    UPDATE_ACTIVITY_VARIABLES_01,
    UPDATE_ACTIVITY_VARIABLES_02,
    SHUFFLE,
    SET_CURRENT_SONG_TIME,
    FILL_PLAYLIST,
    CLEAR_PLAYLIST
}